RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = yes
SRC += qmk_rc.c

#size down   
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
LTO_ENABLE=yes	
